name: wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  #DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: "hassan233/wiki"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build Docker Image
      run: |
        mvn clean package
    
    - name: build docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }} .

    - name: Log in to DockerHub
      run: echo "${{ env.DOCKERHUB_TOKEN }}" | docker login -u "hassan233" --password-stdin

    - name: Push Docker Image to DockerHub
      run: |
        #TAG_NAME="${{ secrets.ENVIRONMENT }}-backend-1.0.${{ github.run_number }}"
        docker push ${{ env.IMAGE_NAME }}:latest
